version: '3.8'

services:

  ngnix:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - app
      - db
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d

  db:
    container_name: db

  app:
    container_name: app