version: '3'
services:
  app:
    build: .
    container_name: cnpj-app
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
  db:
    image: postgres:16
    container_name: cnpj-postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: cnpj-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis-data: