version: '3'

services:

  #Database Service
  db:
    image: postgres:16
    container_name: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cnpj
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    # Redis Service
  redis:
    image: redis:6.0-alpine # Use Redis version 6.0 Alpine for smaller image size
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G

  # Application Service
  app:
    container_name: app
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ../src:/var/www
      - ../data:/var/www/data
    ports:
      - "9000:9000"
    working_dir: /var/www